version: "2.4"

volumes:
  prj.db:
    driver: local

networks:
  prj.network:
    driver: bridge

services:

  build:
    image: "${DOCKER_UTIL_IMAGE_NAME}"
    build:
      context: ..
      dockerfile: ./__DOCKER_UTIL_DIR__/${DOCKER_UTIL_ENV}/Dockerfile
    container_name: "${DOCKER_UTIL_CONTAINER_NAME}"
    environment:
      - ENV=${DOCKER_UTIL_ENV}
    working_dir: /app
    ports:
      - "__FRAMEWORK_CONTAINER_PORT__:4000"
    volumes:
      - ../:/app:delegated
  
  dev:
    build:
      context: ..
      dockerfile: ./__DOCKER_UTIL_DIR__/${DOCKER_UTIL_ENV}/Dockerfile
    container_name: "${DOCKER_UTIL_CONTAINER_NAME}"
    env_file:
      - ../environment.env
    environment:
      - ENV=${DOCKER_UTIL_ENV}
      - DATABASE_HOST=${DOCKER_UTIL_DATABASE_HOST}
      - TEST_HOST=${DOCKER_UTIL_DATABASE_HOST}
      - REDIS_HOST=${DOCKER_UTIL_CACHE_HOST}
    ports:
      - "__FRAMEWORK_CONTAINER_PORT__:4000"
    working_dir: /app
    networks:
      - prj.network
    depends_on:
      __depends_on_db__
      __depends_on_cache__
    volumes:
      - ../:/app:delegated
  
  test:
    build:
      context: ..
      dockerfile: ./__DOCKER_UTIL_DIR__/${DOCKER_UTIL_ENV}/Dockerfile
    container_name: "${DOCKER_UTIL_CONTAINER_NAME}"
    env_file:
      - ../environment.env
    environment:
      - ENV=${DOCKER_UTIL_ENV}
      - DATABASE_HOST=${DOCKER_UTIL_DATABASE_HOST}
      - TEST_HOST=${DOCKER_UTIL_DATABASE_HOST}
      - REDIS_HOST=${DOCKER_UTIL_CACHE_HOST}
    ports:
      - "__FRAMEWORK_CONTAINER_PORT__:4000"
    working_dir: /app
    networks:
      - prj.network
    depends_on:
      __depends_on_db__
      __depends_on_cache__
    volumes:
      - ../:/app:delegated

    __DB_TEMPLATE__
  
    __CACHE_TEMPLATE__